sonar.projectKey=activity-manager
sonar.projectName=Activity Manager
sonar.sources=app,database,routes
sonar.tests=tests
sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**
sonar.sourceEncoding=UTF-8
